### ISSUE TITLE
How to schedule AutoUpdate host file in Windows

### ISSUE THREAD

**Issue by qarqun** [ScriptTiger/Unified-Hosts-AutoUpdate#1]
First of all, very big thanks for your hard work in developing this scripts and i'm sure it will benefit others.

Just 1 request, can provide step by step guide on how to schedule a task to update the Unified Hosts daily in Windows OS without user intervention.

Thanks.

**Comment by ScriptTiger** [comment]
Certainly. Windows key+R, type taskschd.msc, enter. Go to Create Task under Actions on the right side. Under the General tab you're going to want to name your task, "Unified Hosts Update" or some such, and under Security options set up the account you want to execute the script. This should be an account that has Administrative privileges, usually SYSTEM for updates tasks. And then check "Run with highest privileges."

Next go to to the Triggers tab and click New. If you want to just set up a daily update, click on the Daily radio button and select the time you want it to go off every day. I would also recommend checking the box "Stop task if it runs longer than" and then 30 minutes should be fine. This is just as a precaution if something hangs. If you have run the script manually first and everything works as it should, then everything should also work just fine automatically, as well. But definitely run it manually first just to make sure.

Next on the Actions tab, once again go to New. The action will be "Start a program" and browse to the location of the Hosts_Update.cmd. In the Add arguments box, put the URL of the blacklist you like to use. For example:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
This URL will update your hosts with the default Unified Hosts with no extensions.  You can get these URLs from the Raw hosts column on Steven Blacks hosts repo README.

If you see anything you want to change on the Conditions tab, you can do so, but I'll just skip to the Settings tab. Check the box "Run the task as soon as possible after a scheduled start is missed." This will make sure you still get updated even if you don't turn your computer on before the update is scheduled for that day. And again check the "Stop the task if it runs longer than" and 30 minutes.

After you have finished setting up the task, hit OK and close out the task creation dialog. If you chose a user other than SYSTEM, you will then be prompted to input the password for the account that will be running the task. Now before finishing, I also recommend running Hosts_Update.cmd manually at this point and removing your Unified Hosts if you have already added it. You can do this by answering N to "Would you like to continue to update it?", and then Y to "Would you like to remove the Unified Hosts from your local hosts file?" If you currently have the Unified Hosts in your hosts file but you did not add it with my script, you must remove it manually because my script will not know where it is in the file. After you have removed your Unified Hosts, right-click on the new task you created and click Run. Wait a few minutes for the task to do its job. The task status does not automatically update, so you must refresh (F5) the task list to see the status, otherwise it will just continue to say "running." Now check your hosts file and see if the script worked and installed the Unified Hosts correctly.

After you do all this, please let us know how your experience went, and I truly hope it is a good one!

**Comment by ScriptTiger** [comment]
After this project has been tested by more people, then I'll include an option to add a daily update task automatically. But for now I don't want to include it just in case something goes wrong and it's automatically doing something every day that we don't want.

**Comment by ScriptTiger** [comment]
More "help wanted" on testing this script before implementing an integrated scheduled task feature within the script.

**Comment by ScriptTiger** [comment]
*Update: I added a schedule/unschedule task option to the script as a last step before exiting. I would still very much appreciate lots of testing for this though and feedback. I only added it because I started to think it was misleading to call it "AutoUpdate" if it doesn't include a scheduled task to actually automatically update.

**Comment by qarqun** [comment]
yes, indeed the 'autoupdate' was misleading..that's why i highlighted it.  :)

Feedback:

1. schedule/unschedule task installed/removed successfully without issue.
2. host file 'auto' updated daily as per schedule task setting configured.
3. however, if i insert new entry inside the ignore.txt file (whitelist), the task scheduler will not update the host file with that new entry. It will only update together if there is updated version of stevenblack's unified host available.
please note  that the stevenblack's host file will not updated daily.

**Comment by ScriptTiger** [comment]
Because adding entries to the ignore list must be done manually, from an IT perspective manual tasks are better to stay manual. So if I mix your manual entry in an ignore list with an automatic update task, I don't know if something will go wrong or not because I am not actively checking it. So from my perspective manually running the script and telling it to "update anyway" and forcing an update manually is safer for the end user than waiting for it to run automatically and something bad happening. Basically if you are manually adding entries to the ignore list, it's better to "update anyway" manually and check the hosts file to make sure you get what you want before you let it start running automatically and doing something you don't want. I hope that makes sense. I'll keep this issue open and see about getting more feedback on this.

**Comment by qarqun** [comment]
Yes it totally make sense. 👍  better running manually the script for ignore list..

thanks man!

**Comment by ScriptTiger** [comment]
And after you run the script, answer Y to "open the hosts file" when the script is done and make sure the entry you made is not there.

**Comment by qarqun** [comment]
> And after you run the script, answer Y to "open the hosts file" when the script is done and make sure the entry you made is not there.

yes confirmed.

**Comment by ScriptTiger** [comment]
By the way, I am sorry to ask so many questions, but I just want to make sure my information is complete. It's also good for others to read the progress too, so I hope I am not being too annoying.

**Comment by ScriptTiger** [comment]
I updated the  script to track whenever changes are made to the ignore list and it will automatically update now. Let me know if that solves it. I don't like to make things automatic unless I know 100% it's safe, especially when working with system files and admin privileges. If something goes wrong, it can go very wrong. So I like to take my time with automation tasks and make sure the script checks many different things before doing something.

Note: The first time you run the script with the new changes, it will say your ignore list has not been applied because it has not yet added the tracking information to your hosts file. If you have a scheduled task, it will just automatically add the information to your hosts and update your hosts file.
