### ISSUE TITLE
Script cannot connect to the internet if only "Run As" Administrator

### ISSUE THREAD

**Issue by dnlsrl** [ScriptTiger/Unified-Hosts-AutoUpdate#11]
How to reproduce:

* Run script as administrator
* Script throws the following error:

```
This script cannot connect to the Internet!
This script requires an active Internet connection to update your hosts file!
```

The thing is, there are no Internet issues, and it's not my first time running the script.

**Comment by dnlsrl** [comment]
So, it appears the script will execute only and only if the current user is an administrator, not if you're calling it as an administrator in an account with restricted privileges. That's what solved my issue, go to the admin account, change the privileges of the target account, and try again.

**Comment by ScriptTiger** [comment]
Hmm... To be honest I have never logged into my Administrator account once and always run things that need privileges as Administrator because it's just a security best practice, so this can't be replicated for me. What operating system are you on? Windows UAC has changed a great deal over the various operating systems, so it could be an OS-specific issue. Thank you very much for pointing this out. If we can get some more feedback on this issue, I am not sure if we will be able to work around it in the script, but we can at least well document it for users that are likely to experience this issue.

**Comment by dnlsrl** [comment]
Not to log into the Administrator account per se, but for your current user to have administrator privileges. My problem was that the user I was running the script from had limited privileges, so every time I needed to install something UAC will prompt me for a password.

The script works with UAC on, but not when the user's profile is not an administrator. Convert the user's profile temporarily with an administrator account (any) and poof, magic.

Using Windows 10 latest version.

**Comment by ScriptTiger** [comment]
Can you try disabling your firewall, any anti-virus you may have, and any file locking software and test it? Some rules can be account-specific. Do you have any other programs that may be monitoring connections and/or access to certain files?

**Comment by dnlsrl** [comment]
Hmm, no, the computer was clean, I use to run the script before installing other programs. As for the antivirus, I was using the default, but never occur to me to disable it nor the firewall. Hopefully tomorrow I'll get another computer to test this on. I'll report back.

> Some rules can be account-specific.

That must be what is happening here. It's probably looking for the %LOCALAPPDATA% directory but the user it's trying to run upon and the one provided aren't the same.

**Comment by ScriptTiger** [comment]
The built-in UAC system for windows shouldn't be finding a problem with that, but if you have third-party software it is definitely possibly it could be getting confused there and restricting access. Of course Windows has proven to have wildly random differences in places you wouldn't expect, so I wouldn't rule out something that is built into Windows either. I'd love see what you find in further testing so I can include something about this in the readme.

**Comment by ScriptTiger** [comment]
Also, just in case it helps with your investigation, I would also note that this script recently changed from using wget to using BITS on March 22 (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/commit/f286612b5fb1d1e74eff811992a16393e7f5e4cc) in order to drop all third-party binaries. It was tested in a variety of environments and seemed safe enough to roll out, but this may be a result of using BITS. Now I don't see any immediate problems with a default Windows setup, but many people disable BITS or set up custom permissions along with any other Windows update/download service for privacy/security reasons. So maybe you might want to check into your BITS service settings a bit and see if any permissions might be preventing the script from using it. For example, maybe the service is not set to automatically start and the script doesn't have access to manually trigger it.

**Comment by dnlsrl** [comment]
So, it's been a while, but I've finally made further testing.

I used a computer with Windows 7 in a clean state (does installing updates count as "clean state"?) with no third party programs other than the network drivers. User1 is the default user and it has administrator privileges with a password. User2 is a standard user with no privileges and is where I'll be running the script. I also disabled the firewall and there is no working antivirus. The BITS service appears as Initiated and Running with a StartupType set as Automatic (system-wide)

Same results. Run the script within User2 session and the UAC prompt requires the User1 password, enter the password but the script is unable to connect to Internet. The script runs OKAY within User1 with normal UAC prompt without disabling firewall.

**Comment by dnmTX** [comment]
@dnlsrl  did you try to run the script on User2  with right click "run as administrator" ?

**Comment by dnlsrl** [comment]
Yes, that was how I ran it. Sorry I didn't mention it.

**Comment by dnmTX** [comment]
ok....what about Event Viewer,there should be something there to indicate where the error is coming from.

**Comment by dnlsrl** [comment]
The event viewer doesn't appear to record anything about it, but I must admit that I find it hard to use it, so please bear with me.

* Under Windows logs > Application, there are no events at the time of running the script
* Under Application and services logs > Microsoft > Windows > Bits-Client, there's an informational event with the description "The BITS service created a new job" but no error messages
* Nothing under Application and services logs > Microsoft > Windows > UAC

Unless there are other categories I missed, the event viewer doesn't appear to have much data on the script execution.

**EDIT:** It does have to do with the BITS service with an unprivileged user. I just changed the privileges of the user, ran the script and the event viewer is spitting out events under Application and services logs > Microsoft > Bits-Client while running the script.

**Comment by ScriptTiger** [comment]
So at this point is BITS only actively logging or have you gotten it to work successfully with the script? If it's not yet working, have you tried adjusting the service permissions? If you're not sure how to do this, you can google "change Windows service permissions" and you should be able to find plenty of how-tos on it. I am having a bit of a situation at the moment and don't have an environment to test and modify the script on, but once I get everything back in order I can modify the script to also check and adjust service permissions as needed. Or I may just put a check and allow the automatic update to run immediately after using the script since the scheduled task uses system-level permissions and should not be affected by this, and it may also not be wise to change the service permissions in everyone's case since BITS could conceivably be exploited. Until then if we can pinpoint the steps you do to correct this, we can put them in the readme. Also, thanks again for all of your effort put into this so far, it is very much appreciated!

**Comment by dnlsrl** [comment]
To be clear:

* BITS is an enabled, active service even in the session without privileges
* Running the script right-clicking, and providing another user's password still didn't work, and the event viewer doesn't give an error message, only an informational one saying "The BITS service created a new job".
* If, on the other hand, I change the user's privileges and run the script, the script runs OKAY and the event viewer logs several events.

> If it's not yet working, have you tried adjusting the service permissions? If you're not sure how to do this, you can google "change Windows service permissions" and you should be able to find plenty of how-tos on it.

I'll be checking on this, just got a new device to work on.

So I just tried a few things and got new findings but I think I got BITS destroyed from the computer (cannot get it to work again) 😂:

* While reading the script source, I tried both `Start-BitsTransfer -source %url% -destination %location%` and `bitsadmin /transfer "" %url% %location%` manually on an elevated cmd.exe and PS and both threw an 0x800704DD, with the PS interface describing an error saying "Start-BitsTransfer: The operation being requested was not performed because the user has not logged on to the network."
* According to this [documentation](https://docs.microsoft.com/de-de/security-updates/windowsupdateservices/18127392), "The SENS service is not receiving user logon notifications. BITS (version 2.0 and up) depends on logon notifications from Service Control Manager, which in turn depends on the SENS service. Ensure that the SENS service is started and running correctly".
* Tried changing both the logon user AND the permissions to the BITS service, but none of those will work.

I'm getting literally thrown out of the office as I'm typing this, so this is all I can add, I hope it helps at least a little. kay gtg bye

**Comment by ScriptTiger** [comment]
Lol, I really appreciate the effort, but I don't want you to break anything in the process :P I have been thinking about it further and I think I will make the on-demand run optional when you are running the script. As I said, the scheduled task itself shouldn't be affected by this. Can you confirm that your scheduled task is working properly and updates daily as it should?

**Comment by dnlsrl** [comment]
Yes, the scheduled task works alright.

**Comment by ScriptTiger** [comment]
I just pushed an update to address this. I am really open to other ideas on how to address this though. Do many people feel uncomfortable if they cannot update the hosts file interactively on-demand with the script? I could schedule a task to run as soon as the script is finished, but it won't be interactive and will just run in the background. And this issue only affects certain users that have permission issues with BITS and not everyone.

Also, @dnlsrl, if you could just let me know if the script is functioning now and give me your feedback, it would be much appreciated. You should be able to configure everything, but just not be able to update the hosts while you are using the script and will just wait for the daily update to happen. It's a bit like Microsoft updates, you tell them to run "now," but they really just run whenever, so I guess it's in keeping with Windows traditions :P

**Comment by dnlsrl** [comment]
Hello,

Thanks for addressing this, I really don't mind changing the users' permissions to run the script, I just happened to discover the script didn't work under certain conditions. It's good to have an alternative solution, this way there's no real need to change profile permissions to use it; so I'll try it soon and report on it.

**Comment by ScriptTiger** [comment]
No worries, every situation is an important one and I am sure many people are prone to fall into a similar situation. I'd like it to be as versatile as possible, so it really does help to expand the user base.

I'll keep this issue open for your feedback, no rush.
