### ISSUE TITLE
Slow to connect on computer restart

### ISSUE THREAD

**Issue by Austen-Oberheu** [ScriptTiger/Unified-Hosts-AutoUpdate#17]
I've found it takes a couple minutes for the network to connect on my computer after running this. After it is connected everything works fine but when the computer is restarted I have to wait for awhile before it will connect to the network. Any ideas on what is causing this?

**Comment by ScriptTiger** [comment]
Try using a compression level of 9 when you run the script and let me know if that helps.

**Comment by ScriptTiger** [comment]
As this is a pretty common problem, I'll just assume this is resolved for now with my above comment. If this didn't help, please let me know and I'll reopen this.

**Comment by nonetrix** [comment]
Never noticed this on Linux after giving Windows 11 a try this happened, I guess whatever Windows uses to parse the hosts file is poorly written, but then again who expected there to be such a big file, I guess? Interesting

**Comment by ScriptTiger** [comment]
Thanks for commenting, @nonetrix!

As you say, after extensive research here and on Steven Black's repo, the root of the problem seems to be the way Windows parses the hosts file. The issue seems to be more directly correlated with line count and less so just file size in general. So, when you reduce the line count, the problem also diminishes.

When you put things into perspective, a few tens of thousands of lines taking up only a few megabytes is seriously not that big of a deal, even with the worst of indexing algorithms. I'm not sure how Windows handles this, but it seems like it could easily be improved upon. Most modern networkable devices have a hosts file and only Windows has a problem indexing it.

That being said, aside from this particular issue persisting on Windows 11, does everything else work as expected?
