### ISSUE TITLE
flushdns

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#19]
I would like to suggest that `ipconfig /flushdns` be added to the script just before exit.

**Comment by ScriptTiger** [comment]
Others have also suggested this, even though it has actually already been included from the start. Is there any reason you feel as though it's not working? Are you experiencing any delay or other issues that prompt you to suggest this? There are stronger and more volatile ways to deal with the DNS client cache, but the small size of the file doesn't seem to lend itself to need anything stronger than just `ipconfig /flushdns`.

**Comment by ScriptTiger** [comment]
I'll close this for now since there is no actual issue here, but feel free to continue the conversation later with me here to let me know exactly what kind of issue you're experiencing, as I think perhaps there might be an issue that you are just articulating incorrectly since your specific suggestion of implementing `ipconfig /flushdns` has been included in the script from the start, as I said.
