### ISSUE TITLE
.cmd emptied

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#21]
for the second time now, I have gone to script to run it manually (because of a new addition to custom.txt) and I've found out that the file is now empty. Like literally 0kb file names Hosts_Update.cmd, I'm guessing something went terribly wrong during auto-update or something when the task was run automatically.

**Comment by ghost** [comment]
after downloading it again and running it, the .cmd file is now completely gone. deleted somehow..

**Comment by ScriptTiger** [comment]
Okay, first off I will just let everyone else know the issues we are now having are only related to if you are using the new interactive offline mode. If your script has always worked just fine and you've never had any issues with BITS and you just let the scheduled task do its job and don't run the script manually, then none of these issues will affect you and you don't have to worry about your automatic updates, etc.

@horusra, I have now pushed another update to hopefully resolve updating issues in the future. The new update process is now far less volatile. However, if you are still having issues, let me know. As I am not sure where your package fell off the wagon, I would recommend **backing up your custom and ignore files** and then either using git to sync everything up or manually syncing it from the ZIP:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/archive/master.zip

Once these critical issues are resolved, I'd also like to discuss https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/20#issuecomment-426514661 with you, as well, to get your feedback on those other new features.

**Comment by ScriptTiger** [comment]
As per the readme:

> https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/archive/master.zip  
**There have been critical updates to how the script updates itself in order to make the process safer and more consistent. If your script is crashing or experiencing issues immediately after you execute it while it is trying to check its version, you will need to backup your ignore.txt and custom.txt and manually update your package either by redownloading the above ZIP file or using git.**

I realize this is probably a huge annoyance for those users that don't use git, but I am trying to make the script as safe as possible for multiple different environments and new critical problems have been coming to light that have been unavoidable to fix. Again, my apologies. Please continue to give me your feedback so we can continue development and improve the project further so hopefully things like this don't happen in the future.

**Comment by ScriptTiger** [comment]
@dnlsrl, as this is also a continuation of the issues you had raised in https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/11, maybe you could also give some feedback on the current state of things, if you're available to. Some new features are listed in https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/20#issuecomment-426514661.

**Comment by ScriptTiger** [comment]
Not to take silence as consent here, but it has been a few months since any follow-up and we have only been receiving positive feedback, so I will take this issue to be solved. As always, I'm always open to reopen it later if need be.
