### ISSUE TITLE
hosts file corrupted, pc bricked

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#22]
all I know is that I stopped getting internet to work (pinging IP addresses of google worked, but pinging their domain didn't).
Then I opened the hosts file and it had countless markers of **END OF UNIFIED SOMETHING SOMETHING over and over again. Then I left it as it were and ran the script again. To no avail. 

Then when I restarted my pc, windows would get stuck on "logging in" forever. Installation dvd startup fix couldn't fix it. resetting cmos either.
I had to boot a windows installation dvd, then use its file browser to delete the hosts file and the cmd script, and then windows logged in with no problem.

Idk what went wrong with this script, but it went wrong in a big way somehow.

**Comment by ScriptTiger** [comment]
Was this with a version of the latest script? I rewrote a few critical things since the last time you posted an issue to try to better anticipate some of the problems you were having. Do you see anything related in your event logs? Did you also delete the schedule task?

I think in the future just booting into safe mode, logging in, and removing the script that way should also work and would not require a Windows disk.

I would much appreciate any more details you can provide about the incident, and in the meantime I will review the script a bit more for things that could have caused this. Usually issues as critical as this arise from process interruptions, like just closing the script while it is running and not going through the prompts to exit the script properly or simultaneously opening separate instances of files the script is actively using. I have tried to build the script to anticipate most common problems, but as this is the first issue of it's kind and no clear cause as of yet, it may take some time to build in any additional error-handling needed to resolve this issue.

Thanks, as always, for your continued feedback and I hope we can figure this out shortly. Anyone else suffering from similar issues, or have any thoughts of their own on this, is more than welcome to add feedback to this issue, as well.

**Comment by ScriptTiger** [comment]
As with your other issue (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/21), I'm closing this for now, but feel free to reopen at a later date with any follow-ups.
