### ISSUE TITLE
More source options

### ISSUE THREAD

**Issue by spirillen** [ScriptTiger/Unified-Hosts-AutoUpdate#24]
Hi @ScriptTiger have been following you around like a google stalker :smiley:  and then came to this script and read your code in the cmd.

As i found this as a good code base for users who runs windows systems and wan't to do blocking via hosts file.

But what came across my hard is it seems one-sided when i came to the choice of source of hosts file, not that there are anything wrong with @StevenBlack project (quite the opposed), but what if a user would like to have the choice of which source[s] they would like to rely on?

So I would give my 2 cents to a suggestion: 
have the you're script read it's sources from a file like your white/black list...

**Comment by ScriptTiger** [comment]
I've had this suggestion before and this would have to be a separate repo by itself as a general hosts file manager/updater. This script uses only Steven Black's blacklists because it provides a high degree of consistency which my script relies on to make the process as easy and as fast as possible while also allowing for a reasonable degree of optionaility. Allowing for any given blacklist would open the door to more format variance as well as more processing as the script would then also have to aggregate the blacklists and remove duplicates and all that other fun stuff that Steven Black so kindly does for us already. Basically I would have to drop all the features that rely on the known factors specific to Steven's hosts files which help to make this script so easy and add in functionality to handle all the unknown factors that come with using any given hosts files as sources.

I have already opened a local repo and it's on my to-do, but it will definitely be a repo of its own and this repo will forever be dedicated to Steven Black. It's not just managing/updating a hosts file, it's also about the magic that happens in Steven Black's python script that this repo is married with.
