### ISSUE TITLE
Unbound refuse instead of redirect

### ISSUE THREAD

**Issue by pkirkovsky** [ScriptTiger/Unified-Hosts-AutoUpdate#25]
Could we set the Unbound list to refuse requests instead of redirect?
This would shrink the file size considerably:
`local-zone: "1493361689.rsc.cdn77.org" redirect`
`local-data: "1493361689.rsc.cdn77.org A 0.0.0.0"`
vs
`local-zone: "1493361689.rsc.cdn77.org" refuse`

Refusing queries also make collecting blocking stats easier (using `num.answer.rcode.REFUSED`)

**Comment by ScriptTiger** [comment]
It's been a best practice to explicitly redirect to 0.0.0.0 since both `deny` and `refuse` both answer if there is a match from local data. Basically if there is a local data match, `deny`, `refuse`, and `redirect` all redirect based on a local data entry match, and `deny` and `refuse` do not necessarily `deny` or `refuse` everything right off the bat as one might expect if there is a loose local data match that one may be unaware of floating around. Obviously in most cases there won't be a match from local data, but it's just a best practice to cover your bases and not leave room for any ambiguity and just explicitly create a local data entry match for 0.0.0.0 and explicitly redirect to it to speed up the process of ending the lookup faster.

I realize best practices often involve redundant safeguards, but they are intentionally so in order to ensure the highest levels of safety. If there is, however, a misconception to this logic, I am still open to hearing your thoughts. I definitely get where you are coming from as far as a stats perspective though, but at this point I still don't think sacrificing best practices to make stat collection easier would be the best option.

Please refer to the official Unbound documentation for further information on the above referenced technicalities:
https://nlnetlabs.nl/documentation/unbound/unbound.conf/

**Comment by ScriptTiger** [comment]
I also seem to recall older versions of the Unbound config actually giving clear examples of blocking ad servers using this method, although newer versions are written a bit differently and only state the following:

```
# You can override certain queries with
# local-data: "adserver.example.com A 127.0.0.1"
```

It still seems clear providing an explicit override entry is still advisable just to catch everything. Although in the example 127.0.0.1 is used, obviously the industry best practice would be 0.0.0.0.

**Comment by ScriptTiger** [comment]
As far as concerns about file size, are people having a problem with this? As Unbound is slowly replacing BIND as the standard, I would expect the few megabytes the current blacklists take up are nothing compared to what Unbound capabilities are. But I can't claim to be an expert on Unbound and actually have more experience with BIND in the past, so any further input on this would also be appreciated.

**Comment by ScriptTiger** [comment]
@pkirkovsky, another way to reduce the list size would be to remove all redundant subdomains. Right now my Unbound list uses the following format:

```
local-zone: "zarget.com" redirect
local-data: "zarget.com A 0.0.0.0"
```

Can you tell me if this would block `zarget.com` and all subdomains (i.e. `www.zarget.com`) automatically with just these entries? If it does, I can go ahead and remove all of the subdomains from the list, which would dramatically decrease the file size. If you're not sure, can you test it real quick on your Unbound setup and get back to me?

**Comment by spirillen** [comment]
Another more modern way should be using `always_nxdomain`

From https://nlnetlabs.nl/documentation/unbound/unbound.conf/:
```
            always_nxdomain
                 Like static, but ignores local data and returns nxdomain  for
                 the query.
``` 
This will speed up the reply to the app querying, and tell it that the `spy domain` does not exist, stop waiting for response.

An ex line would looks like these
```python
local-zone: "facebook.com" always_nxdomain
local-zone: "google.com" always_nxdomain
local-zone: "gstatic.com" always_nxdomain
local-zone: "improving.duckduckgo.com" always_nxdomain
local-zone: "googlesyndication.com" always_nxdomain
local-zone: "google-analytics.com" always_nxdomain
local-zone: "googleapis.com" always_nxdomain
local-zone: "googledomains.com" always_nxdomain
local-zone: "doubleclick.net" always_nxdomain
local-zone: "microsoft.com" always_nxdomain
```

**Comment by ScriptTiger** [comment]
@spirillen, thank you! The ignoring local data part was just what I was looking for! So now the list can at least be reduced by half just getting rid of the `local-data` entries.

Now the other question I have is do these `local-zone` entries apply to all subdomains automatically, as well? If I have `local-zone: "zarget.com" always_nxdomain`, will this block `local-zone: "www.zarget.com" always_nxdomain`, as well?

**Comment by spirillen** [comment]
@ScriptTiger well there have been some writing about that in the past, but give me a couple of minuts, and i'll test it....

**Comment by spirillen** [comment]
Test result:

In my `zones/adblock.local` i've added 

```python
local-zone: "zarget.com" always_nxdomain
```

dig results looks like:

```bash
dig zarget.com www.zarget.com

; <<>> DiG 9.11.5-P1-1ubuntu2.5-Ubuntu <<>> +nocookie zarget.com www.zarget.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 18464
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;zarget.com.                    IN      A

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 28 01:02:37 CEST 2019
;; MSG SIZE  rcvd: 39

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11062
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.zarget.com.                        IN      A

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 28 01:02:37 CEST 2019
;; MSG SIZE  rcvd: 43
```

So basically yes, subdomains still seems to be killed :( 

For test of dig after removing `zarget.com`

```
dig zarget.com www.zarget.com 

; <<>> DiG 9.11.5-P1-1ubuntu2.5-Ubuntu <<>> +nocookie zarget.com www.zarget.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61182
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;zarget.com.                    IN      A

;; ANSWER SECTION:
zarget.com.             60      IN      A       143.204.247.72
zarget.com.             60      IN      A       143.204.247.86
zarget.com.             60      IN      A       143.204.247.63
zarget.com.             60      IN      A       143.204.247.109

;; Query time: 527 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Aug 28 01:08:45 CEST 2019
;; MSG SIZE  rcvd: 103

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49201
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.zarget.com.                        IN      A

;; ANSWER SECTION:
www.zarget.com.         60      IN      A       143.204.247.86
www.zarget.com.         60      IN      A       143.204.247.72
www.zarget.com.         60      IN      A       143.204.247.109
www.zarget.com.         60      IN      A       143.204.247.63
```

And this is one of the reasons that I use a combination of Dnsdist and pdns-recursor in my own RPZ DNS server project. (They also understand regex for domain blocking :tongue:

**Comment by ScriptTiger** [comment]
> So basically yes, subdomains still seems to be killed :(

Why did you do the ":("? For me this is a good thing because it means I can remove all of the redundant subdomains from the list and make the list even smaller. Right? I want to see a lot of ":) :) :)" lol :P

**Comment by spirillen** [comment]
@ScriptTiger because if you have a example.net but would allow access to alpha.example.net then you have a issue and the RFC is pretty clear about this. According to the RFC you should make the record as `example.net CNAME .` and to include all subdomains `*.example.net CNAME .`. According to the RFC you can actually also whitelist a subdomain by `ex.example.net CNAME pass-true`

That the :(

but you are right killing subdomains by the second lvl domain is a line saver

**Comment by ScriptTiger** [comment]
Yeah, we were talking with Paul Vixie himself, one of the DNS imagineers and RFC writers, about that with an issue regarding the RPZ format, https://github.com/StevenBlack/hosts/issues/451, and he made it pretty clear that just blocking all subdomains and probably white-listing any special cases on an as-needed basis is the best way to handle it.

**Comment by ScriptTiger** [comment]
When @pkirkovsky first brought this issue up, I wasn't really happy with his suggestion, but I did agree something could probably be done. So thanks, @spirillen, for saving the day with this! I'll go ahead and close this issue.

**Comment by spirillen** [comment]
@ScriptTiger You welcome, and I can tell you it have reduced my db from 1,6mill records to about 600k records by using the RPZ nxdomain. So happy scripting :smiley:

**Comment by ScriptTiger** [comment]
That sounds about right. Are you using my RPZ files?

**Comment by spirillen** [comment]
Actually not 100% sure, but I'm following this project as my little sister still haven't updated to Linux, and I've installed [unbound](https://nlnetlabs.nl/projects/unbound/about/) on Microsoft's PC and found this project could have a future in my [toolbox](https://gitlab.com/rpz-zones/toolbox), But please add your list to the [external list](https://gitlab.com/my-privacy-dns/external-sources) zones, and I'll check up on it

**Comment by ScriptTiger** [comment]
All of my Unbound lists are now up to date with the new improvements.

I checked out your link for the external list zones. I'll have to get back to you on this at a later date. I haven't used GitLab too extensively in the past, other than just cloning some projects and doing some offline forks. I just created an account there, but I'll have to set up all of my key pairs when I get a bit more free time to look at this more extensively.

**Comment by spirillen** [comment]
Super @ScriptTiger .... after I started using Gitlab I most admit it didn't take me too long to move all project's there.  However and read this as a friendly "warning":

Gitlab's Issue board is rather good,  but, but , but.... there anti-spam system isn't optimized for projects like these, and will often request a reCapture verification through the Google reCapture. This mean you have to think about if you like to or not, to have your contributors to be forced to have access to google (Google is 100% blocked on my network), and by that being tracked by Google..

Otherwise I would recomment Gitlab vs Bitbucket/Github. And you can use the 'Settings -> Repository -> Mirroring repositories' to keep 2 or more remote repos up to date from the master..

**Comment by spirillen** [comment]
PS: @ScriptTiger have now been given [Developer](https://gitlab.com/help/user/permissions) access to the [My Privacy DNS Firewall](https://gitlab.com/my-privacy-dns) Group
