### ISSUE TITLE
'hosts' filters differs when using compression

### ISSUE THREAD

**Issue by EPiC-APOC** [ScriptTiger/Unified-Hosts-AutoUpdate#27]
Compression 9 gives another outcome in 'hosts', then when using no compression (1) in blocklist (hosts).

**i.e.**
`Hosts_Update.cmd https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts 9` (max compression), then these next lines do NOT show up in 'hosts':
```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

If I use: 
`Hosts_Update.cmd https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts 1` (no compression), then these same lines DO get into the 'hosts' file, as expected.

So somehow these lines get skipped when using compression (9), this is what I get into my 'hosts' when I use compression (9):
```
# Project releases: https://github.com/StevenBlack/hosts/releases #   # =============================================================== 
# Custom host records are listed here. # End of custom host records. # Start StevenBlack #=====================================   # Hosts contributed by Steven Black # http://stevenblack.com 
```

**Comment by ScriptTiger** [comment]
Good catch. Let your script update itself automatically and let me know if the new changes work for you.

As an additional note, I had been including some of the loopbacks and multicast addresses in the default ignore list just to avoid conflicts with the more commonly used addresses, but I decided on removing them in this update since I have had a handful of people thrown off by it. If anyone has any issues to report on this, please do so.

**Comment by EPiC-APOC** [comment]
yes, that does the trick, now it's (again) like one would expect (Y)

Thank your for the support
