### ISSUE TITLE
ignorelist ignored

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#31]
on the left is my ignore.txt on the right is my hosts file.
![image](https://user-images.githubusercontent.com/17074394/65926331-0f052980-e3f5-11e9-8a50-99a348b9a0a4.png)
I literally copied the list of hosts I didn't want blocked, from the hosts file to the ignore.txt and yet the script (after updating) still puts these hosts in the hosts file.

**Comment by ScriptTiger** [comment]
I can see from your other issue, https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/30, that you were running an older version of the script that was not compatible with the newer update system. Can you please confirm this issue again with the latest version of the script?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/17074394/66089065-f4aa8780-e57d-11e9-953e-4784ee3b1958.png)
running the latest version of the script (even manually updated the script, and even deleted everything in the hosts file. Still has items from my ignore.txt in it

**Comment by ScriptTiger** [comment]
The problem was from my script appending spaces to the line endings of uncompressed hosts files. You then copied the line as it was in the hosts file, with a trailing space, which then was not recognized because the line in Steven Black's hosts file does not have trailing spaces.

I have updated to 1.26 to fix this issue, so your hosts file will no longer have trailing spaces and you can copy and paste as expected. However, you must manually update your ignore list to remove the trailing spaces that are already present, as my script does not edit your personal ignore in any way.

**Comment by ScriptTiger** [comment]
@horusra, I'm closing this issue for now, but please let me know if you have any other issues related to this and I'll open it back up. Thanks again for all of your feedback, it's really been helping a lot!
