### ISSUE TITLE
Exit with meaningful exit codes

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#36]
The script currently exits with a success exit code (0), no matter what happens.
For example, if I'm not an admin and the script does nothing, it would still report success.
This should be fixed so whenever the script encounters any failure (e.g. can't create task) it exits with a non-zero exit code (ideally you could even differentiate, e.g. `1` means not admin, `2` means couldn't create task etc).

**Comment by ScriptTiger** [comment]
I just made a commit, but I have not pushed it as a release yet because I feel as though there might be some more room for suggestions here. In order to test the developmental version, please manually download the developmental script (https://raw.githubusercontent.com/ScriptTiger/Unified-Hosts-AutoUpdate/master/Hosts_Update.cmd) to replace your current script, right-click and edit the downloaded script file to change `set V=1.29` to `set V=1.28`, and then execute it under your test conditions, using the following exit code key as a reference.

Exit codes:
0=No errors
1=The script did not have appropriate administrative permissions
2=Something is wrong with the closing markings within the hosts file (i.e. `#### END UNIFIED HOSTS ####`)
3=A general error with the hosts file markings
4=Emergency stop status due to something critical being broken or under repair
5=The script could not connect to the Internet for whatever reason
6=BITS is either not installed or could not be found

Let me know what you think! If it's ready for release as is, I'll go ahead and push it.

**Comment by ohadschn** [comment]
I tested cases `0` and `1` and they look good, I'll take your word for the others :)

**Comment by ohadschn** [comment]
However this would primarily matter in conjunction with https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/38

**Comment by ScriptTiger** [comment]
I know what you're getting at with #38, but exit codes is case closed.
