### ISSUE TITLE
Alert on task failure

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#38]
Currently, if the task fails for whatever reason, there is no notification.
This means that I can go on for 20 years having an out of date HOSTS file without knowing, because the script is failing every day and I don't know about it.
I suggest alerting the user somehow so they can't miss a failure. For example - leave a modal dialog open that notifies about the error. Or send an e-mail, or create a toast notification. Something...

**Comment by ScriptTiger** [comment]
I really like this feedback, thanks! I'll keep this one open and review it later. Such modal dialog would not be possible directly using the standard CLI interpreter, but could be easily done with a temporary VBScript or integrating another open-source binary to be able to leverage Windows APIs for balloon notifications, etc. However, using any of these methods, incorporating the built-in scripting engine for VBScript or third-party open-source binary to leverage Windows APIs, would also come with an increased security risk, so these issues would first have to be balanced out.

**Comment by ohadschn** [comment]
As I said in the other issue, moving to PowerShell would present so many benefits, easily popping out a modal window is but one of countless others...

**Comment by ohadschn** [comment]
How about this - if `powershell.exe` is available do something like this:
`powershell.exe -ExecutionPolicy Unrestricted -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); [System.Windows.Forms.MessageBox]::Show('Error updating HOSTS file', 'Error')"`

If `powershell.exe` isn't available, do something simpler. Some options:
1. Try calling VBScript if available.
1. Call some tool to show a toast notification.
1. Launch a different batch script that shows the error and pauses for user interaction.
1. Copy a different batch script that shows the error and pauses for user interaction to the startup folder so it will pop up the next time the user logs in (or create a task for the same).
1. Copy a file named HOSTS_UPDATE.ERROR to desktop so the user will notice.
1. Make a few beeps.
1. Do nothing.

At any rate, in the vast majority of cases where PowerShell would be available, users would be aware of the issue. And in the rare cases where PowerShell isn't there you can make a good enough best effor per one of the options above.

**Comment by ScriptTiger** [comment]
> How about this - if powershell.exe is available do something like this:
> powershell.exe -ExecutionPolicy Unrestricted -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); [System.Windows.Forms.MessageBox]::Show('Error updating HOSTS file', 'Error')"

I like this. I am not opposed to using PowerShell if it's available. I actually have PowerShell handle BITS by default if it's available because obviously downloading the files is the most essential core function of the script, so handling it properly is key.

> If powershell.exe isn't available, do something simpler. Some options:
> 
> Try calling VBScript if available.

I like this, too. I'll stop there for now, as these two should be sufficient for most users.

**Comment by ohadschn** [comment]
Sounds good!

BTW the cherry on top would be to mention the actual error in the message box (since you already which it is, per your work in  https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/36), so instead of just `Error updating HOSTS file` you could write `Error updating HOSTS file: could not access hosts file on GitHub at address ...` etc.

Stop me if I'm asking too much :)

**Comment by ScriptTiger** [comment]
> Stop me if I'm asking too much :)

Too much? I could hardly pop a dialog up saying "Something went wrong, figure it out." I know SOME people that work at CERTAIN companies don't mind doing that (i.e. "You can't write to this file because maybe it's in use or not available or read-only or doesn't exist or lost in space."), but I would personally find that highly annoying. And since I am making this for me, constructive dialog would be a given, so I believe we are on the same page there.

> ...so instead of just `Error updating HOSTS file`...

I'll also make a note for posterity that I never recommended that.

**Comment by ScriptTiger** [comment]
> `powershell.exe -ExecutionPolicy Unrestricted -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); [System.Windows.Forms.MessageBox]::Show('Error updating HOSTS file', 'Error')"`

Can you revise this real quick to not wait for user input, like how a Start-Job cmdlet works by running in the background?

**Comment by ScriptTiger** [comment]
I implemented your suggestion above for when the script is running unattended in the background. If you run the script stand-alone, it doesn't really need them since it outputs to the console.

Still looking forward to a revision, as stated in my above comment, to improve it a bit. But other than that, let me know what you think.

**Comment by ohadschn** [comment]
It looks like `Start-Job` doesn't work, I think the `powershell.exe` process dies before the job gets scheduled. However you can just use `start`: `start powershell.exe -ExecutionPolicy Unrestricted -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); [System.Windows.Forms.MessageBox]::Show('Error updating HOSTS file', 'Error')"`

Having said that, why not wait for user input? If such an error occurs, I would be happy if the script stopped and waited for my input.

**Comment by ohadschn** [comment]
As for the actual behavior, I tested 1.31 and it works when executed from the command line, but unfortunately not when executed from the task scheduler (which is the most important scenario).

I did find something that works though:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msg

In our case the powershell invocation would be replaced with something like:
`msg * Error updating HOSTS file: %ERROR%`

**Comment by ohadschn** [comment]
BTW, the reason `System.Windows.Forms.MessageBox` fails is due to the script not running in `UserInteractive`. It should be possible to work around using [MessageBoxOptions](https://docs.microsoft.com/en-us/dotnet/api/system.windows.messageboxoptions?view=netframework-4.8) (`DefaultDesktopOnly` / `ServiceNotification`) but I couldnt' get it to work (tried using WPF, same result).

**Comment by ScriptTiger** [comment]
> Having said that, why not wait for user input? If such an error occurs, I would be happy if the script stopped and waited for my input.

If you have the script open in a console interactively and are using the `/DFC` switch for debugging, there's no reason for any dialog box since you can see it all happening live in the console and can debug it after it closes. The dialog box strictly makes you aware of an error that happened in an instance of the script that is being run not interactively, i.e. by the task manager. This means the console is not accessible to the user anyway, so they would not be able to debug anything whether a dialog pops up or not.

If there were actions I could give the dialog to fix the problem, that would be cool and make it worth waiting for user input. However, right now all of the exit errors are rather critical and there is no button I can give the dialog to fix your Internet connection or give the actively running script admin permissions after it's already started. All of those errors are better handled after the script is exited and run again later after the issue is resolved.

> In our case the powershell invocation would be replaced with something like:
> `msg * Error updating HOSTS file: %ERROR%`

`msg` is even more commonly disabled than PowerShell. Not directly, but by way of its Remote Desktop dependencies. However, this is the simplest choice and would work on older systems running XP that don't have PowerShell. I used to use this quite frequently in my scripts written before getting into hardened systems, then I just forgot about it. Nice catch!

I have implemented `msg` in the latest 1.31 script, please try it again and let me know.

**Comment by ScriptTiger** [comment]
I just released all of these changes in the last release, so you can just pull the latest script automatically and test it.

**Comment by ohadschn** [comment]
> If there were actions I could give the dialog to fix the problem, that would be cool and make it worth waiting for user input. 

I agree, just saying it doesn't really matter either way, so no point in putting any special effort in waiting or not waiting for user input.

> `msg` is even more commonly disabled than PowerShell. Not directly, but by way of its Remote Desktop dependencies. However, this is the simplest choice and would work on older systems running XP that don't have PowerShell. I used to use this quite frequently in my scripts written before getting into hardened systems, then I just forgot about it. Nice catch!
Trust me I tried every possible alternative - WinForms, WPF, even UWP toast notification. They all fail because the script is running under the `NT AUTHORITY\SYSTEM` in non-interactive mode. If you want to make the notification mechanism more resilient I see two options:
1. Run the task under the user's context (not great in terms of security and reliability)
1. Send an e-mail, great solution with two options for implementation:
  a. Use an e-mail sending service (SendGrid has a free plan that includes 100 e-mails / day forever, will probably be enough for the foreseeable future). 
  b. Have the user provide their user, password, & SMTP server (they can just open a disposable account on GMail or something so they don't care to about the password in plaintext). Here's how it can be done from PowerShell: https://stackoverflow.com/a/2250309/67824

> I have implemented `msg` in the latest 1.31 script, please try it again and let me know.

Works great, thanks!

**Comment by ScriptTiger** [comment]
I have set up PowerShell e-mail notifications for personal use in the past, but I don't think it's necessary in this case. Since `msg` works fine for most cases, e-mail notifications would seem mostly for server admins. However, anyone that has left an automated task running on an unattended server of some kind and wants e-mail notifications probably already has a system monitor software of some kind to do that and can just integrate with the new exits codes. I also just don't like putting too much PowerShell, as I have stated before, just because this isn't a PowerShell script.

Case closed! Thanks, again, for all your feedback!

**Comment by ohadschn** [comment]
Technically speaking using a service like SendGrid you don't need PowerShell, it's just [one simple cUrl call](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html): `curl -X "POST" "https://api.sendgrid.com/v3/mail/send" -H "Authorization: Bearer YOUR_API_KEY" -H "Content-Type: application/json" -d "[YOUR DATA HERE]"`

So for example you could bundle your script with a native Windows `curl.exe` (just one small [EXE](http://curl.haxx.se/download.html), no dependencies) and call the above.

As for the 100 e-mails / month limit, even that can be easily increased significantly (without asking users to provide their own key) - if you create it via the Azure portal you can send 25,000 monthly e-mails for free: https://portal.azure.com/#create/Sendgrid.sendgrid_azure

**Comment by ScriptTiger** [comment]
cURL supports the following formats:
DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET and TFTP.

Wget on the other hand supports these:
HTTP, HTTPS, and FTP.

When you're dealing with binaries in git, they get archived as a single static glob and can't take advantage of diff'ing like text files can, which is precisely what git was designed for, text file source code. So when binaries become absolutely necessary in git, you should always pick the absolutely smallest possible ones.

When it comes time to update a binary, unlike text files that can simply apply a small diff patch that is a fraction of the size of the entire file and only a record of the changes, older binaries simply get unlinked into git history and take up space, compounding wasted space every time you update them because the old ones just get unlinked but are still in history while the new ones get added and linked. So nothing is gotten rid of and you just end up having more and more of these static globs floating in history that never get used and weigh the repository down. I'll also say that both Wget and cURL have had several major security updates since first creating this repository, so this would have been a very real problem for this repo.

There are tools like BFG (https://rtyley.github.io/bfg-repo-cleaner/) to help clean up old unused globs, but you should really only do this when absolutely necessary because playing with git history irrevocable damages your repo's integrity. If you're interested in playing with one such repo that has little integrity, feel free to check out my GitHub Pages repo (https://github.com/ScriptTiger/scripttiger.github.io). In the case of my GitHub Pages, there is no need for such git integrity because it's primary purpose is to serve files via GitHub Pages and git history is not important for that particular repo.

All that being said, the initial version of this script did utilize Wget initially since it is dramatically smaller than cURL and had only the protocols this script needed, but was phased out due to community cries for the elimination of third-party binaries, which came to be a cornerstone of this script's mission. You can check out the initial script here: https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/tree/afe7e15d595aa111db6fe24ff846375134c6d474

**Comment by ScriptTiger** [comment]
Just as an aside to all that, you may also be interested in my IP repo (https://github.com/ScriptTiger/IP) which still utilizes Wget since it works better for that user base. The `Data_Update.cmd` works with MaxMind's RESTful API to update the local MaxMind files using each user's individual license key for authorization. Obviously in this case the RESTful API doesn't need to POST or require any specific header arguments and could work just fine using BITS like this script since it's just a normal GET fetch.

**Comment by ohadschn** [comment]
1. I am well aware of how git works and its limitations, but your arguments are purely theoretical. In the real world, a checked-in 3MB file will be fine even after 900 version updates (I estimate close to zero impact).
1. I'm not convinced `wget` is smaller (the download [here](https://eternallybored.org/misc/wget/) for it is >30% larger) but if that's the case, the above argument is even stronger.
1. You can always just use BITS to download the most recent version of `curl` / `wget` and have nothing checked in. You are already downloading a file (HOSTS), which can be just as dangerous if not more, so you are not introducing any new conceptual risk.
1. Are you sure any of the cUrl security vulnerabilities were relevant to this super basic and battle-tested scenario of a single POST call, which involves no secrets whatsoever and no processing of the response? I find it highly unlikely.

**Comment by ScriptTiger** [comment]
I rest assured knowing Microsoft and the Azure team, minus one apparently, agree with me:
https://docs.microsoft.com/en-us/azure/devops/repos/git/remove-binaries?view=azure-devops

> Best Practice Considerations
> It saves a lot of work to make sure that large files stay out of the main repository in the first place. With that in mind, here are some common sense best practices for the team to keep in mind:
> 
> Do's
> 
> Do commit changes frequently. You can always fix them up later with a squash or rebase.
> Do use branches to isolate your changes. Branches are cheap and private, and merging is simple. You can also back up changes on a branch by pushing it to the server.
> Do use a naming convention when publishing topic branches. Name the branch "users/<alias>/<branchname>". This will help group your branches and make it easy for others to identify the "owner".
> Do remember to push your changes. Commit != Checkin. (Commit + Push) == Checkin.
> Do consider using .gitignore for large binaries so that they aren't added to the repo in the first place - more information here.
> Do consider using NuGet or TFS version control to store your large binaries.
>
> Don'ts
> 
> Don't rebase after pushing. Rebasing pushed commits in git can be bad because it forces everyone else in the repo to rebase their local changes - and they won't be happy if they need to do this. Rebasing pushed commits on your own personal branch, even if pushed, isn't a significant deal unless other people are pulling those commits.
> Don't commit binaries to your repo. Git doesn't compress binary files the way that TFVC does, and because all repos have all of the history, committing binary files means permanent bloat.

Just "some common sense best practices," as they say.

I also don't like the idea of sneaking third parties in via BITS, as it's been discussed as a community in a couple different repos and the general consensus is no third parties. There's a variety of reasons for this and whether or not you agree with it or not, it makes the 99.9% of other users feel more comfortable. If I was going to do this by myself, I would have never published all of this to GitHub in the first place. However, I highly value user feedback, including yours, because it contributes towards making a better product for us all.
