### ISSUE TITLE
Paths with spaces need to be encapsulated with apostrophes for PowerShell (BITS)

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#40]
Hi and first thanks for the great script :)

I had some trouble with this and long story short, it was because I had the script in a path with a space. Turns out that downloads would fail and it would run endless retries.

This was caused by the destination paths for the BITS transfers, being encapsulated in quotes (") but powershell wants apostrophes (').

Naturally, I could just run it from a path without spaces, but still, the script can be made resilient to this issue fairly easily.

I feel like a pull request is kinda overkill to change 8 characters - plus, maybe you'd rather fix it a different way.... so here are the offending lines - I hope this is OK:

Direct BITS calls:

Line 113:
`%BITS_FROM% %GH%/master/VERSION %BITS_TO% "%CTEMP%" > nul || call :Connectivity`

`%BITS_FROM% %GH%/master/VERSION %BITS_TO% '%CTEMP%' > nul || call :Connectivity`

Line 284:
`	%BITS_FROM% %URL% %BITS_TO% "%CTEMP%" > nul || call :Connectivity`

`	%BITS_FROM% %URL% %BITS_TO% '%CTEMP%' > nul || call :Connectivity`

Calls to `:Download`

Line 54:
`	call :Download %GH%/%COMMIT%/README.md "%README%" readme`

`	call :Download %GH%/%COMMIT%/README.md '%README%' readme`

Line 137:
`	call :Download %GH%/%COMMIT%/%CMD% "%UPDATE%" update`

`	call :Download %GH%/%COMMIT%/%CMD% '%UPDATE%' update`

Line 404:
`if not !REMOVE!==1 call :Download %URL% "%CTEMP%" hosts`

`if not !REMOVE!==1 call :Download %URL% '%CTEMP%' hosts`

Obviously, there may be other ways to use apostrophe rather than quote, but I'll leave that in your very capable hands.

I hope this helps, and thanks again :)

**Comment by ScriptTiger** [comment]
> This was caused by the destination paths for the BITS transfers, being encapsulated in quotes (") but powershell wants apostrophes (').

Nice catch! I've had several PowerShell enthusiasts review my script, but they never caught that.

> Naturally, I could just run it from a path without spaces, but still, the script can be made resilient to this issue fairly easily.

Easy-peasy, I've already pushed a fix in 1.33. Please allow your script to update itself and make sure it works for you and let me know what you think!

> I feel like a pull request is kinda overkill to change 8 characters - plus, maybe you'd rather fix it a different way.... so here are the offending lines - I hope this is OK:

A good PR is a good PR, regardless of how long or short it is :P Some would argue my entire script is overkill since it's using the classical Windows command processor and not PowerShell, so overkill is what we do here! I did have to make some small tweaks to your suggestion since this script uses PowerShell when available, but also can use BITS directly, also, and apostrophes throw a wrench into direct calls not using PowerShell. But it was a great suggestion nonetheless and I would have most certainly taken a PR from you, I would have just reviewed and edited your PR before committing it to my branch. Be confident! This repo could use some more contributors, as right now people might think I am overprotective or something. But the truth is I have accepted 100% of the PRs sent in, which has only been one in the last 2+ years.

Thanks again, and waiting for your feedback on the fix in 1.33!

**Comment by ghost** [comment]
Yours is a much more elegant fix, and it works a charm, thanks!
