### ISSUE TITLE
Write log file

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#42]
I'm getting intermittent errors where if I re-run manually everything works fine.

It would be great if text logs, detailing the operations taken by the script, were written to somewhere like %TEMP% (the `msg` error is a good start, but not enough to debug the issue).

**Comment by ScriptTiger** [comment]
Something like making an optional switch to just dump the regular output to a file when running the script in unattended mode should work?

**Comment by ScriptTiger** [comment]
Added an optional `/log:<path>` argument, it must be placed before the URL and compression level. Manually update your script, decrement the V number inside the script, and try it out and let me know your feedback before I push it as a release.

**Comment by ohadschn** [comment]
Works great!
A couple of suggestions:
1. Allow specifying only `/log` in which case something like this would be used: `/log:%TEMP%\UAHU-%DATE:~-4%.%DATE:~4,2%.%DATE:~7,2%-%time::=.%.log` (e.g. `"C:\Windows\Temp\UAHU-2020.01.24-21.44.59.74.log"`).
1. When creating the task (using `SchTasks`), create a log by default using the above option.

**Comment by ScriptTiger** [comment]
> Allow specifying only /log in which case something like this would be used: /log:%TEMP%\UAHU-%DATE:~-4%.%DATE:~4,2%.%DATE:~7,2%-%time::=.%.log (e.g. "C:\Windows\Temp\UAHU-2020.01.24-21.44.59.74.log").

I was debating the default log location. No matter how I thought about it, the average user doesn't know how to get to the temp folder. Despite being able to just type %temp% into the run prompt, most people get lost around AppData since it's both hidden and also presents a fork in the road with Local, LocalLow, and Roaming, so it's not as intuitive as just specifying your own location. I might do some more work on this in a bit though, so stay tuned.

> When creating the task (using SchTasks), create a log by default using the above option.

I am actually pretty firmly against this idea at the moment. Wherever there is a persistent log, there must be log management, which isn't on the roadmap at the moment. And it's not that hard to just edit your scheduled task to put in  `/log:<path>` if you are in need of debugging. If you know how to do that and opt into keeping a log, I trust you know how to manage your own log, since you're opting into that, as well.

Log management is both a security risk as well as just a practical risk. For people running this script on, for instance, a cluster of VMs without a proper log management cycle in place and limited resources, the log could easily fill up and lock up the entire system at a given point. And in today's world it's silly to assume someone with a cluster of VMs knows better, given the barrier to entry is so low to acquiring such virtual resources these days and also given the abundant real-world proof presented us with all the misconfigured cloud resources out there owned by huge corporations one would assume might know better but get hacked every other day.

**Comment by ohadschn** [comment]
> I was debating the default log location. No matter how I thought about it, the average user doesn't know how to get to the temp folder. Despite being able to just type %temp% into the run prompt, most people get lost around AppData since it's both hidden and also presents a fork in the road with Local, LocalLow, and Roaming, so it's not as intuitive as just specifying your own location. I might do some more work on this in a bit though, so stay tuned.

Actually even %TEMP% in the run prompt won't work, because the admin user has a different TEMP folder: `C:\WINDOWS\TEMP`. The average user might not know that, but the important thing is for that log to be there, so when the need does arise, that user can look it up (possibly by asking here).

> it's not that hard to just edit your scheduled task to put in /log:<path> if you are in need of debugging. If you know how to do that and opt into keeping a log, I trust you know how to manage your own log, since you're opting into that, as well.

The big advantage here would be precisely for those people who don't know (or don't want to invest in learning) how to edit their tasks and add such arguments.

> Log management is both a security risk as well as just a practical risk. For people running this script on, for instance, a cluster of VMs without a proper log management cycle in place and limited resources, the log could easily fill up and lock up the entire system at a given point. And in today's world it's silly to assume someone with a cluster of VMs knows better, given the barrier to entry is so low to acquiring such virtual resources these days and also given the abundant real-world proof presented us with all the misconfigured cloud resources out there owned by huge corporations one would assume might know better but get hacked every other day.

My logs are 285 bytes, running once a day that's about 1MB in a _decade_. I don't think that would ever be a problem, but if you really wanted to you could just make it cycle - e.g. use the same file name and overwrite, or only include the date without the year in the file name and thus retain ~364 days back.

**Comment by ScriptTiger** [comment]
> Actually even %TEMP% in the run prompt won't work, because the admin user has a different TEMP folder: C:\WINDOWS\TEMP. The average user might not know that, but the important thing is for that log to be there, so when the need does arise, that user can look it up (possibly by asking here).

Most users that have given feedback here, while running the script interactively, run the script from a user account that is a member of the local admins group. In these cases the `%TEMP%` directory is used. The `%SystemRoot%\TEMP` is only used when the system is running the script, i.e. the scheduled task is running.

> The big advantage here would be precisely for those people who don't know (or don't want to invest in learning) how to edit their tasks and add such arguments.

I don't feel as though those people should be debugging anything. In cases where people are having critical problems, just running the script interactively and copying and pasting what they see from the console into an issue here has worked for everyone else so far, and would seem a lot easier than playing with a log file.

> My logs are 285 bytes, running once a day that's about 1MB in a decade. I don't think that would ever be a problem, but if you really wanted to you could just make it cycle - e.g. use the same file name and overwrite, or only include the date without the year in the file name and thus retain ~364 days back.

I'll be honest with you, if someone was to put some magic characters into some of the script parameters, it's easy to derail the entire script output and dump several megabytes worth of data into the log on one run. I haven't put that much programming into input validation and for the most part my script assumes you are feeding it valid data. I may feel comfortable doing something for this in the future, but right now I just don't feel comfortable with it.

**Comment by ohadschn** [comment]
> Most users that have given feedback here, while running the script interactively

Keep in mind that the `msg` popup is a new feature, so many people might have had the task fail and never knew about it. Seeing as the scheduled task is arguable the most important feature of this script (out of date malware lists are very dangerous), it stands to reason you would start getting reports in the vein of "I get this error message every day at 3 AM...".

If you even wrote a single non-timestamped log file (each run overrides the last, so no danger of overflowing), debugging such issues would be much easier. As a bonus, you could put the location of the log file in the `msg` error message (solving the issue of where to look).

**Comment by ScriptTiger** [comment]
I'm going to close this issue for now. However, as reports start flooding in that require me to revisit this, I will use the suggestions you have stated here as a guideline. As this hasn't happened yet, I can't really know what the average user's reaction will be to the `msg` prompts or what the workflow will look like to resolving their issue and if logging will really be the best option, etc., etc. I just need more feedback from others before I can follow through on these points, and my current stance is based solely on the feedback at large that I do currently have.

**Comment by ScriptTiger** [comment]
I revisited this topic and now allow for `/log` to set a default log location as `log.txt` within the script home directory and NOT a `temp` directory.

Check it out and let me know your feedback.

I am not  revisiting the issue of log management at this time, as I still feel as though that should be handled by the user. Since the log name can be easily scripted, the user themselves can set up log management and run the script using something like `Hosts_Update /log:C:\Hosts-Logs\%DATE%-log.txt`, or however they want to organize it using custom variables, like `%DATE:~-4%` for yearly logs, `%DATE:~4,2%` for monthly logs, etc.

Another problem with implementing log management inside of the script is that regional settings can cause the `%DATE%` variable to change formats from system to system and the year, month, day, etc., will switch positions and it cannot reproduce a reliable and consistent logging method across all of the script users.

**Comment by ohadschn** [comment]
This is great, thanks!
I hope I'm not pushing my luck, but how about adding `/log` to the generated task?

**Comment by ScriptTiger** [comment]
> I hope I'm not pushing my luck, but how about adding /log to the generated task?

I'm not going to implement any mechanism within the script itself to activate logging at this time, as this goes hand in hand with the log management issue I described above. I still feel as though implementing this manually is the safest route as well as shifts clear liability to the end user. I have been managing servers a long time and have changed my personal style of managing logs from time to time, and have even changed it from application to application on occasion. End users need to take clear responsibility for their own log management and be aware of all of its aspects.

For me logs can be a rather serious issue and I don't want any part of it to just be a haphazard decision made on a whim and forgotten about later. This is a similar reason as to why I don't support automatic updates with my DualServer blacklist updater, because it's a network service possibly affecting multiple systems and it's never recommended to update such things automatically, you should always at least be monitoring the process live in case issues arise. I know the average user may not be a sysadmin or whatever, but these are just basic principles I live by and push down to the end user to live by, as well, if they decide to use my work.
