### ISSUE TITLE
Echo download command to console/log

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#46]
The task failed with the following log:
```
Sun 01/26/2020 @  3:00:06.03: Checking for script updates...
Sun 01/26/2020 @  3:00:06.36: The Unified Hosts is already installed in your local hosts file
Sun 01/26/2020 @  3:00:06.37: Checking for Unified Hosts updates...
Sun 01/26/2020 @  3:00:07.19: Waiting 10 seconds before retry...
Sun 01/26/2020 @  3:00:27.20: Download Retry 1: benchmark...
Sun 01/26/2020 @  3:00:27.98: Waiting 20 seconds before retry...
Sun 01/26/2020 @  3:01:08.15: Download Retry 2: benchmark...
Sun 01/26/2020 @  3:01:08.90: Waiting 40 seconds before retry...
Sun 01/26/2020 @  3:02:28.19: Download Retry 3: benchmark...
Sun 01/26/2020 @  3:02:28.92: Waiting 80 seconds before retry...
Sun 01/26/2020 @  3:05:08.20: Download Retry 4: benchmark...
Sun 01/26/2020 @  3:05:13.14: Waiting 160 seconds before retry...
Sun 01/26/2020 @  3:10:33.15: Download Retry 5: benchmark...
Sun 01/26/2020 @  3:10:38.19: Waiting 320 seconds before retry...
Sun 01/26/2020 @  3:21:18.20: Download Retry 6: benchmark...
Sun 01/26/2020 @  3:21:23.18: Failed downloading https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts!
Sun 01/26/2020 @  3:21:23.23: Cleaning temporary files...
```

There is nothing wrong with my internet, so I don't know why the download would fail. Rerunning the task manually from the Task Scheduler UI, it succeeds in the first attempt in a total of less than 3 seconds.

I thought a good debugging start would be to echo the exact command used for downloading. Even better, echoing that command's stdout/stderr as well could go a long way to help us understand what went wrong (maybe something like `powershell Start-BitsTransfer -source ... > logfilename`).

**Comment by ScriptTiger** [comment]
I just made a new commit that redirects all commands previously sent to null device, except for timeouts, to the log file if configured, otherwise they are just sent to null device as usual. So it's a bit more than just downloads, but just beating you to the punch.

I won't send them to the console because I have had issues in the past where users report issues if there's too much output even if everything went successfully because they think there might be a problem. Also, my script issues several commands that intentionally invoke errors on certain systems to better test out the environment, and these outputs are especially worrying for some users, even when the script is designed to handle them and ultimately succeeds. Making a switch to output such errors to the console seems redundant if it can already dump an even more complete account to a log file.

Let me know and I'll push a release.

**Comment by ohadschn** [comment]
Failure cases look good! I can see the `Start-BitsTransfer` exceptions when I intentionally kill my connection.

However I still think a log line like `Executing: powershell.exe -Command "Start-BitsTransfer -source https://raw.githubusercontent.com...` would be helpful to be 100% sure what's going on, even in apparent success cases.

**Comment by ScriptTiger** [comment]
> However I still think a log line like Executing: powershell.exe -Command "Start-BitsTransfer -source https://raw.githubusercontent.com... would be helpful to be 100% sure what's going on, even in apparent success cases.

I am a bit OCD to a certain degree and I don't like this idea simply because if I start a precedent to start logging every command, I'll have to do it for everything just to keep things consistent. I also don't think it's necessary since the command output is sent to the log, all of the output from all of the previous checks are sent to the log, as well as we all already know what the command is that's being sent just from reading the script. I am 100% certain both you and I would 100% be sure of everything going on just from reading the log.

**Comment by ohadschn** [comment]
I can relate to the OCD, and in my scripts I indeed wrap command calls in functions that print them out. 

Barring that, my concrete concern was that I didn't know whether BITS or PowerShell were used, so just adding a trace saying something like "PowerShell detected" would be a fair compromise I feel.

**Comment by ScriptTiger** [comment]
I wrapped the command calls for all commands with logged output, so wish granted. HOWEVER, please, please, please test everything you can think of before confirming the latest commit because I ended up getting carried away and also did some code reduction and consolidation at the same time. So just make sure as sure as you can be before letting me know, and then I'll push this as a release.

**Comment by ohadschn** [comment]
Now I feel bad for enforcing your OCD 😂
Will test and report back

**Comment by ohadschn** [comment]
I tested the script, emulating network failures for good measure. Everything looks perfect:

```
Mon 01/27/2020 @ 16:12:06.58: Initializing...
Mon 01/27/2020 @ 16:12:06.62: Executing: bitsadmin /list

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.

Listed 0 job(s).
Mon 01/27/2020 @ 16:12:06.67: Executing: powershell $host.version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145     


Mon 01/27/2020 @ 16:12:06.93: Checking for script updates...
Mon 01/27/2020 @ 16:12:07.26: The Unified Hosts is already installed in your local hosts file
Mon 01/27/2020 @ 16:12:07.27: Checking for Unified Hosts updates...
Mon 01/27/2020 @ 16:12:07.33: Executing: powershell invoke-webrequest https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts  -outfile 'C:\WINDOWS\TEMP\Unified-Hosts-AutoUpdate\ctemp'
invoke-webrequest : The remote name could not be resolved: 'raw.githubusercontent.com'
At line:1 char:1
+ invoke-webrequest https://raw.githubusercontent.com/StevenBlack/hosts ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Mon 01/27/2020 @ 16:12:08.09: Waiting 10 seconds before retry...
Mon 01/27/2020 @ 16:12:28.13: Download Retry 1: benchmark...
Mon 01/27/2020 @ 16:12:28.18: Executing: powershell invoke-webrequest https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts  -outfile 'C:\WINDOWS\TEMP\Unified-Hosts-AutoUpdate\ctemp'
invoke-webrequest : The remote name could not be resolved: 'raw.githubusercontent.com'
At line:1 char:1
+ invoke-webrequest https://raw.githubusercontent.com/StevenBlack/hosts ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Mon 01/27/2020 @ 16:12:28.80: Waiting 20 seconds before retry...
Mon 01/27/2020 @ 16:13:08.31: Download Retry 2: benchmark...
Mon 01/27/2020 @ 16:13:08.47: Executing: powershell invoke-webrequest https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts  -outfile 'C:\WINDOWS\TEMP\Unified-Hosts-AutoUpdate\ctemp'
Mon 01/27/2020 @ 16:13:15.86: Downloaded benchmark successfully
Mon 01/27/2020 @ 16:13:15.96: Cleaning temporary files...

```

**Comment by ScriptTiger** [comment]
Thanks for testing and confirming! Just pushed the release.
