### ISSUE TITLE
Change the use of ping to something else because some networks block its use

### ISSUE THREAD

**Issue by savyajha** [ScriptTiger/Unified-Hosts-AutoUpdate#57]
Some people (like yours truly) are on networks that block the use of pings. It might be a good idea to change that to checking the value of the HTTP response code instead for better compatibility. I'm no powershell guru but I found [this link](https://dotnet-helpers.com/powershell/how-to-check-response-code-from-a-website/) which talks about doing something of that sort.

If one were to use bash and curl (on Linux) for the same, I'd do something like:

```
#!/bin/sh
RETVAL="$(curl -s --max-time 2 -I https://google.com | sed 's/^[^ ]* *\([0-9]\).*/\1/; 1q')"
if [ "$RETVAL == "2" ] || [ "$RETVAL == "3" ]; then
    <run the script if google is connectable>
fi
```

Maybe it would be possible to implement something similar?

**Comment by ScriptTiger** [comment]
Hey, @savyajha! Thanks for the feedback! And I apologize for the slow reply, I have been a bit tight on time and resources lately, so my attention here has been lacking.

> Some people (like yours truly) are on networks that block the use of pings. It might be a good idea to change that to checking the value of the HTTP response code instead for better compatibility.

I've just extended the interactive connectivity check to include a simple optional HTTP request if pinging fails. Please manually update your script to the newest version and let me know if it addresses your issue!

Please note, these changes have been committed to the repository so you can test them, but they have not been pushed in a public update yet. Because of this, unless you manually edit your script to change `set V=1.48` to `set V=1.47`, it will automatically detect your version is a developmental version and attempt to backdate your script to 1.47. Again, please let me know as soon as you have had time to confirm these changes, at which point I will push these changes in a public update.

> I'm no powershell guru but I found this link which talks about doing something of that sort.

This script has a high focus on both compatibility and security, and for those reasons PowerShell is not a dependency for this script to function. I believe in this case a simple HTTP GET request will suffice.

**Comment by savyajha** [comment]
Hey @ScriptTiger, no worries about the lateness at all! I later found out that the issue would only happen if the script was run interactively. Once the task was installed then it seems that the script does not use pings.

Your solution works perfectly even with interactive usage (where the issue was actually manifesting). Would it not be better to completely replace pings with HTTP GET requests? It simplifies the script a bit.

**Comment by ScriptTiger** [comment]
Thanks for confirming, I just pushed the update!

> Would it not be better to completely replace pings with HTTP GET requests? It simplifies the script a bit.

Since even most secure environments don't disable outbound ping/ICMP, since that is still traffic originating from within the enclave and trusted and can be easily tracked by a firewall (obviously disabling ICMP traffic within an enclave is more common to prevent internal discovery), that's not really a common problem for most users of this script.

The more common problem for many users, however, is being in an extremely high-latency environment where connectivity may go in and out even during the usage of the script. That is why great care has gone into the way downloads are handled, as far as the algorithm for retying failed attempts, etc. Ping/ICMP allows you to get a general connectivity test much better than HTTP because I can send ping/ICMP requests in much more rapid succession and with constant known packet sizes, at least within the constraints of the available environment without employing third-party tools or other applications such as PowerShell.

The assumption is that it's fine for the daily update to fail from time to time because it is running every day and still has a high probability to succeed within an overall reasonable amount of time to keep your system reasonably safe. However, if you are taking the time to manually run the script interactively, the connectivity check is a bit more extensive because you probably have a stronger intention for the script to succeed and are aware of the possible resource implications that means (such as the high CPU usage, etc., that the script takes up temporarily for the time it's processing the new hosts file). Basically, if you are using the script interactively right now, it's assumed right now is probably a better time to update than any other time since you are taking the time to run it yourself, so it tries just a little bit harder to succeed for you than if it's not interactive and just a normal daily update that may or may not be a good time with all the right conditions for success every time.
