### ISSUE TITLE
does this works with a custom or user specified host blacklist?

### ISSUE THREAD

**Issue by dakd2** [ScriptTiger/Unified-Hosts-AutoUpdate#6]
I havent seen any info about that yet

**Comment by ScriptTiger** [comment]
Yes. Your custom entries should not be affected. This script just adds its own entries to the bottom of your existing hosts file and keeps them up to date and doesn't touch anything else in the file. Let me know if it's not working like that though and I'll definitely fix it ASAP.

Also, can you make a suggestion as to how the README should be reworded as to make that more clear to help others in the future?

**Comment by dakd2** [comment]
well since the steven black's hosts seems to have a way to handle custom or user specified hosts blocking on separate or specific files rather than specifing them directly on the windows hosts file, I was not using any custom hosts blocking when I started using this unified hosts autoupdater but I feel like I am gonna need to soon, I was used to the steven black hosts method, but the autoupdater documentation didnt mention anything about that, and the steven black host way to handle custom hosts blacklists doesnt seem compatible as far as I know with this autoupdater

**Comment by ScriptTiger** [comment]
I could mark this as a feature request and add a new file to add custom entries, similar to the ignore.txt custom whitelist. Would that make things easier?

I had never thought of it before because many of the people using the script have never used the Steven Black's Python script and I am assuming are just used to making custom entries in the hosts file itself. However, giving you the option to put them all together in the same directory does make sense for those that want to take advantage of that ability.

**Comment by ScriptTiger** [comment]
I pushed an update with this option included using a custom.txt file. Let me know what you think.

Note: I was trying to steer away from the wording of "whitelist" and "blacklist" here because that's not technically what's happening here and the custom.txt could include any kind of entries and not just entries for 0.0.0.0. And rather than the ignore.txt "whitelisting" anything, it's simply ignoring matching entries and not necessarily "whitelisting" them as far as any actual security systems are concerned. I thought maybe this wording would help people understand what's actually happening so they can better utilize them.

**Comment by ScriptTiger** [comment]
Looking back, @qarqun had actually mentioned this in https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/2, also, but I had overlooked it before as I was distracted and troubleshooting the errors in the script pointed out in the same issue, so my apologies there.

**Comment by ScriptTiger** [comment]
I think I have resolved this, so I'm going to close it. Feel free to let me know if something else should be done with this though, I am always open to suggestions.
