### ISSUE TITLE
Compression fails when empty comment is present in ignore.txt

### ISSUE THREAD

**Issue by Dominic-DallOsto** [ScriptTiger/Unified-Hosts-AutoUpdate#60]
I recently encountered what I assume to be a bug, that if there is an empty comment line in the ignore.txt file the compression of the hosts file fails and I only end up with one entry per line. Obviously this isn't a big deal, but it frustrated me for a little bit until I worked it out.

My ignore file was like the following:

```
# Ignore list written in literal expressions
# These changes will take effect automatically the next scheduled update
# To force changes now, run Hosts_Update.cmd with the "update anyway" option
# If you decide to delete the below entries, DO NOT delete these above comment lines
# If this file is left completely empty, the script will break
# Uncomment the below entry to allow the analytics.google.com domain
#0.0.0.0 analytics.google.com
#
# Note! Only put 0.0.0.0 at the start if it's an exact match
```

The comment by itself on the line causes compression to fail. This still happens if the hash is followed by a space `# `, but not if followed by another character like `#a` or `# ---`.

If it helps, the messages I receive when running the file change slightly if compression has just run successfully or failed.

Run successfully: 
```
Checking for Unified Hosts updates...
Your current ignore list, custom list, or compression level needs to be applied.
Your current preset is to use the following Unified Hosts:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Would you like to just stick with that? [Y,N]?
```

Failed:
```
Checking for Unified Hosts updates...
The Unified Hosts will automatically block malware and adware.
Would you also like to block other categories? [Y,N]?
```

**Comment by ScriptTiger** [comment]
Thanks for the feedback!

Issues surrounding the `ignore.txt` are a popular topic here, so I can totally understand the confusion and frustration. However, this is simply the way the Microsoft Windows `findstr.exe` works. It actually doesn't support comment lines at all. In order to support empty comment lines in the `ignore.txt`, I would need to create an entirely new internal function to filter and parse the `ignore.txt` before reading it. This is something I really don't want to do since the script already must iterate over filtering and parsing the hosts file several times in order to properly format it and already draws a lot of system resources while doing so due to the limitations of Windows batch file scripting.

For additional context, I'll offer a quick example. The following lines are at the top of the `ignore.txt` by default:

```
# Ignore list written in literal expressions
# These changes will take effect automatically the next scheduled update
# To force changes now, run Hosts_Update.cmd with the "update anyway" option
# If you decide to delete the below entries, DO NOT delete these above comment lines
# If this file is left completely empty, the script will break
# Uncomment the below entry to allow the analytics.google.com domain
#0.0.0.0 analytics.google.com
```

Lines beginning with the "comment character" `#` in the above case are actually not interpreted by `findstr.exe` as comments at all and are instead interpreted as active valid literal expressions, just like all the other lines in the file. The `#` comment character is simply used in the file to denote the comments to a human reader, but has no real function beyond that. So, for example, if `#0.0.0.0 analytics.google.com` actually does appear in the real hosts file, it will be filtered out because it is an active valid literal expression entry in the `ignore.txt`.

Also, neither of your provided excerpts from the script output suggest any "failure." For example:

```
Checking for Unified Hosts updates...
Your current ignore list, custom list, or compression level needs to be applied.
Your current preset is to use the following Unified Hosts:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Would you like to just stick with that? [Y,N]?
```

The above excerpt mentions your `ignore.txt` has changed and that it needs to be reapplied to your hosts file, meaning the script must update again and filter the new entries you've made in the `ignore.txt`. And then it goes on to tell you the exact hosts file template you are using from Steven Black's repository and offers you a chance to change it.

Now let's take your next excerpt:

```
Checking for Unified Hosts updates...
The Unified Hosts will automatically block malware and adware.
Would you also like to block other categories? [Y,N]?
```

The above output neither mentions the `ignore.txt` nor what your preference of template is from Steven Black because that information was probably removed by yourself while you were conducting tests on the hosts file, meaning the script has no way of knowing whether the `ignore.txt` has changed at all nor does it know what your preference of template is because that information had been removed from the file and there's no way for it to know that. Thus, the script simply proceeds to assume it needs to conduct a full update with your current `ignore.txt` and prompts you for which template you'd like to use from Steven Black, since it has no "preset" to draw from since that has been removed from the file. So, there is still no "fail" condition here and everything is working as intended.

Again, thank you for your feedback, your interest in the project is definitely appreciated! If you have any further questions or concerns, always feel free to create an issue, no matter how big or small the issue. Thanks, again!

**Comment by Dominic-DallOsto** [comment]
Thanks for the response! I think I understand what you're saying, but maybe I didn't explain clearly enough the problem I encountered. The issue isn't that creating the hosts file failed or anything like that, but just that compressing the hosts file onto multiple lines does not happen, despite me having set a compression level > 1.

I wasn't aware of the limitations of `findstr.exe`. I'm sorry, I'm not super experienced with batch scripting so can't follow exactly what is going on. Correct me if I'm wrong, but it seems like this is the relevant section of code. 

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/eae31d1fc40d2e8d900d66f17e996296ec8282ca/Hosts_Update.cmd#L493-L507

So you're saying that `findstr.exe` gets each line from `ignore.txt`, irrespective of whether or not it is a "comment", and removes any line from the hosts file that contains a partial match? What would happen with a blank comment line? Does it break the logic here somehow? Or would it just remove all comment lines from the hosts file?

And why would this cause compression not to happen? Is it possible the check on line 503 would fail? Or does the compression run but this check not identify that the line is a comment?

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/eae31d1fc40d2e8d900d66f17e996296ec8282ca/Hosts_Update.cmd#L561


> The above output neither mentions the ignore.txt nor what your preference of template is from Steven Black because that information was probably removed by yourself while you were conducting tests on the hosts file, meaning the script has no way of knowing whether the ignore.txt has changed at all nor does it know what your preference of template is because that information had been removed from the file and there's no way for it to know that.

I did not manually edit the hosts file at any point. First, I ran it with `#a` in the `ignore.txt` file and compression set to 9. The output hosts file was correctly compressed. Then I changed the line in `ignore.txt` to `#`. When running the update script, the current list was detected (ie. the "successful" output) and the hosts file is updated. But now, the output hosts file was not compressed - there was only one entry per line. When running the update script the next time, the current list isn't detected (ie. the "failed" output). Does this suggest that the empty comment line in `ignore.txt` causes some comments from the output hosts file to be incorrectly removed, so that the update script cannot later read them?

I hope this helps to diagnose the problem! Again, I'm not experienced with the limitations of `findstr.exe` and whether it is possible to detect and prevent the behaviour I observe here. If not possible, might it be a suitable workaround to add a warning in the documentation or the `ignore.txt` file itself saying not to use blank comment lines?

**Comment by ScriptTiger** [comment]
I apologize for my rashness, you are exactly correct!

The best workaround in this particular situation would absolutely be a notice in the `ignore.txt`, as you've stated. A programmatic solution, while absolutely being possible to implement, would just add additional overhead to this already clunky script.

I'm also in the process of rewriting this script in Go, so continuing to make non-critical workarounds for the shortcomings of the batch file environment is not really a priority for me at the moment. Which is why I may have dismissed this issue too quickly the first time, and I apologize once more for that. I 100% will address critical flaws and maintain this script as needed since it is the only script of its kind not requiring third-party executables, not requiring PowerShell, and therefore does serve as a vital security solution for a niche group of people. However, there are obvious benefits when it comes to both resource management and project management to making this also available as a security solution written in Go, as well, which I plan to write from scratch without any third-party packages in order to continue to uphold that initial commitment to security and reliability.

Thank you, again, for your feedback and I hope the latest update appropriately addresses this issue.

**Comment by Dominic-DallOsto** [comment]
No problem - that looks good. Thanks for all your work!
