### ISSUE TITLE
issue not blocking

### ISSUE THREAD

**Issue by killmasta93** [ScriptTiger/Unified-Hosts-AutoUpdate#63]
Hi
I was wondering if someone could shed some light on the issue im having, Currently installed correctly and i see the blockage on the hostfile, but it seems that the windows uses the DNS first rather then the host file any ideas why?

Thank you

**Comment by ScriptTiger** [comment]
Can you try uninstalling this script by following the prompts to remove, and then try manually updating your hosts file with one of the "IPv4_IPv6" lists from the following page?

https://scripttiger.github.io/alts/

Some Windows users using these block lists, although not using this script, have reported DNS "leaking" where IPv6 is available. Because currently no actual users of the script have reported this problem, the script currently doesn't support IPv6 entries because it automatically doubles the size of the hosts file. Windows is known to have problems parsing hosts files with long line counts, so including this functionality in the script could possibly cause more harm than good for many users who don't have any problems with IPv6. It could be possibly made an optional argument in the future, but, as stated, we just haven't had any actual script users encounter that problem. Windows seems to have wildly different functionality even between systems of the same operating systems and architectures, so making things that work safely and efficiently for all Windows systems is a bit of a balance.

**Comment by killmasta93** [comment]
Thank you so much for the reply, currently we have IPV6 disabled i uninstalled and tried adding manually but still able to access the site it seems that the windows goes first to the DNS server rather then the host file

**Comment by ScriptTiger** [comment]
Can you check the permissions of your hosts file? It should be fine if it's read-only, but the system must have access to at least read from the file. Sometimes if you're manually editing the hosts file, the permissions can get messed up and take your user's permissions and drop permissions to the system. If the system can't read it, it will just bypass it altogether. I think the default permissions should give the system full control, so read, write, modify. But, like I said, it should work with read-only, but just experiment to see if you can get it working that way.

**Comment by ScriptTiger** [comment]
Oh, just an additional note here, too. If you're using a proxy, that may also obviously bypass the hosts file, too. So, check your system settings or any extensions or settings your browser may be using and see if there is a proxy being used. Sometimes some browser extensions say they are "VPNs" but are actually proxies, so be aware of that, as well. Also, not all proxies resolve DNS on the distant end, but by default most modern setups do. If you have a proxy set up and wish to keep it and also use your hosts file, then make sure you have local DNS resolution in place.

**Comment by killmasta93** [comment]
Thank you so much for the reply, correct it was a proxy issue, im looking on how i can configure my WPAD to not affect the local hosts on the computer the rest is working flawless thank you so much

**Comment by ScriptTiger** [comment]
No worries, glad you got it figured out!

If you're running your own local proxy, I also have some block lists available in other formats that you may be able to import so that everyone using the proxy, including your phone and other mobile devices, can get the benefit. Blocking from the proxy itself will also allow you to perform remote DNS resolution and still be able to block bad hosts at the same time.

https://scripttiger.github.io/alts/

If you decide to go the route of local DNS resolution while also using a proxy, remember then that your local DNS queries will not be encrypted by default if you are just using a standard DNS setup. So, keep that in mind and perhaps consider using a DNS over HTTPS (DoT) or DNS over TLS (DoT) solution to keep your DNS queries encrypted. If you are already using Tor, you can also just use the built-in DNS responder that comes with Tor, as well, to encrypt your DNS traffic.

**Comment by killmasta93** [comment]
Thank you so much,
