### ISSUE TITLE
Script uses 30% DNS

### ISSUE THREAD

**Issue by farzadha2** [ScriptTiger/Unified-Hosts-AutoUpdate#64]
Hi
I was wondering if someone could shed some light on the issue im having, Currently recently installed on a windows 10 computer, after installing i rebooted and saw the CPU usage of the DNS 30% it then starts freezing the computer not sure why

Thank you

**Comment by ScriptTiger** [comment]
This is most commonly due to not using "compression." If you have not already, please try using a compression level of 9 when you set up the script and let me know if that helps.

This is not a default setting because most Windows users do not actually have this problem and it's unclear why some do and some don't. However, the problem itself is very clearly line count. So, using a compression level of 9 should address that issue.

**Comment by farzadha2** [comment]
Thank you so much for the reply, Currently when i try to put compression it gets stuck not sure normally how long it takes?

![image](https://user-images.githubusercontent.com/62571297/170630199-59b21542-4d4d-43dd-8a85-450fe955f613.png)

**Comment by ScriptTiger** [comment]
As the comment says in the screenshot, you can expect it to take longer. This script does not use any third-party applications to help it, and it also does not rely on PowerShell. This is intentional because this script is designed for security purposes to operate in a hardened environment where you may not have access to third-party applications or PowerShell. Because of this, the script is relying on only the native command processor environment, which is extremely limited and not anywhere designed for large-scale textual processing. However, despite the clunky process, it does work if given the proper amount of time to let it.

Another aspect to the design if you have automatic scheduling set up is that it checks for updates daily and only updates if a new update is available. If an update is available but the script fails to update, maybe because you didn't leave the system on long enough for it to finish or maybe there was a network problem and the update couldn't be downloaded, etc., it will just try again tomorrow, and the next day, until it can successfully update. As it's not necessary to strictly update it exactly when the update is available, it's fine to just let it update whenever it has time and system resources to do so. It's completely fine to shut down your system in the middle of an update if you don't want to wait, this script is built with safety in mind, unlike the official Windows updates which can corrupt your system if you shut down in the middle. You can also just run the script manually if you prefer to only update exactly when you want to and don't wish to have the automatic scheduling set up.

**Comment by farzadha2** [comment]
Thanky so much i had wait few more mins and it seems that its working flawless

**Comment by ScriptTiger** [comment]
No worries! I'm glad it's working out for you.

Like I said, the process is a bit clunky, but you shouldn't stress out about needing to update it immediately the second Steven comes out with a new list. Just keep it reasonably up to date and that's good enough. Using the hosts file alone for security is obviously not ideal, and it should always be part of a larger security strategy, with each piece both overlapping at points and also complementing each other's gaps, the same way the scales in scale armor work.
