### ISSUE TITLE
Hosts marked properly but still receiving error

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#7]
When I run the `cmd` file as Admin, command window shows the following messages.

```
Checking for script updates...
Your script is up to date

Hosts is not properly marked
Please ensure the following lines mark where to insert the blacklist:

#### BEGIN UNIFIED HOSTS ####
#### END UNIFIED HOSTS ####

Notes: You should only have to mark this once
Updates automatically overwite between the above lines
Would you like to open your current hosts file before exiting? [Y,N]?
```
However, as you can see below, the hosts file begins with the proper marking.

```
#### BEGIN UNIFIED HOSTS ####
# Managed by ScriptTiger's Unified Hosts AutoUpdate
# https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate
# Ignore list: eaedc45a77913a0410250d589a252468
# Custom list: a639fe0920dd7460ff4564c497116689
#
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: March 03 2018
# Extensions added to this file: fakenews, gambling, porn
# Number of unique domains: 67,718
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
# Project home page: https://github.com/StevenBlack/hosts
#
# ===============================================================
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# Custom host records are listed here.
# End of custom host records.
#=====================================
# Hosts contributed by Steven Black
# http://stevenblack.com
0.0.0.0 1493361689.rsc.cdn77.org
0.0.0.0 30-day-change.com
0.0.0.0 2468.go2cloud.org
```
In addition, the latest hosts file from Steven Black is dated March 10 and mine says March 03. However, the script shows that my script is `up to date`.

**Comment by ScriptTiger** [comment]
Can you upload or link a complete version of your hosts file? It's possible the ending markings could be incorrect or there could be erroneous multiple markings later in the file that we aren't seeing from the section you have copied and pasted here.

As far as the script being up to date, the script version is different from the hosts version from Steven Black. The current version of this script is 1.10 and is stored in the VERSION file.

If the script is throwing an error about the markings, it's not getting to the point to check the date of the hosts version from Steven Black yet. However, if your hosts version is old and not the newest from Steven Black, the script will tell you, "A new Unified Hosts update is available!" This is not to be confused with the script version.

**Comment by ghost** [comment]
Thanks for clarifying the distinction between the script and hosts versions. That clears up my confusion.

I deleted my hosts file completely and started over. Hosts file is generated and configured correctly when I run the `cmd` script the first time. So the attached hosts file is dated March 10. However, same errors shows up. Problem is that AFTER the hosts file is first configured and I re-run the the `cmd` script the second time, I get the error I mentioned in the OP. If it helps I have got some domains added to `ignore.txt` and `custom.txt` files which are also attached.

[ignore.txt](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/files/1800829/ignore.txt)

[custom.txt](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/files/1800830/custom.txt)

[hosts.txt](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/files/1800832/hosts.txt)

**Comment by ScriptTiger** [comment]
Thank you tremendously for catching this! The issue is that your custom.txt, a feature just recently added, did not terminate with an empty line as it had when I was testing it and the script didn't account for this and simply appended the closing tags onto the last line of your custom.txt without creating a new line. I just fixed this and pushed an update. This was definitely a script-breaker, so thank you again for catching this!

    0.0.0.0	www.msftncsi.com#### END UNIFIED HOSTS ####

Should be

    0.0.0.0	www.msftncsi.com
    #### END UNIFIED HOSTS ####

Since you have already been affected by this issue, can you please either manually delete the unified hosts section from your hosts file or create a new line for the closing tag in your current unified hosts section and try running the script again? When you run the script in the future, this problem shouldn't happen again. However, because it has already affected your closing tag, you must manually edit it just this once.

**Comment by ghost** [comment]
It does work flawlessly after I edit the hosts file as you suggested. Thank you for the quick reply and resolution! No more error messages.

**Comment by ScriptTiger** [comment]
Also, @bisherbas, in your particular case, if you manually deleted your hosts file and are relying entirely on the unified hosts in an otherwise new and empty hosts file, you might be missing some critical entries that are being ignored in your current ignore.txt.

    127.0.0.1 localhost
    127.0.0.1 localhost.localdomain
    127.0.0.1 local
    255.255.255.255 broadcasthost
    ::1 localhost
    fe80::1%lo0 localhost
    0.0.0.0 0.0.0.0

The reason these are ignored by default is to prevent conflicts with/duplicates of pre-existing hosts entries you might have before applying the unified hosts. Steven Black's hosts files were designed to replace the current hosts file, while this script works with your existing one and simply appends to it. If you are using only the unified hosts with no pre-existing entries, you may not want to be ignoring the lines presented above. My apologies for causing such heartache and I hope you can correct it as needed.

**Comment by ghost** [comment]
Thank you for the reminder @ScriptTiger. I indeed deleted the default entries inadvertently but I just copied the above lines back into the `hosts` file. I guess I am all set now. Thanks again for all the great help.
