### ISSUE TITLE
Multiple URLs

### ISSUE THREAD

**Issue by azumukupoe** [ScriptTiger/Unified-Hosts-AutoUpdate#72]
Could you add support for multiple URLs? I'd like to add some rules that are not covered by https://github.com/StevenBlack/hosts

**Comment by ScriptTiger** [comment]
If you're trying to do anything more advanced than what this script already provides, I'd recommend checking out Hosts-BL (https://github.com/ScriptTiger/Hosts-BL). With Hosts-BL, you can pipe multiple hosts files to it and Hosts-BL will automatically concatenate them, remove duplicates, and compress the output to 9 domains per line, all of which is adjustable and entirely optional.

As Unified-Hosts-AutoUpdate works only within the default Windows environment without any dependencies, it is extremely limited in what it is capable of doing both reliably as well as safely, and it is for this reason it is specifically designed and intended only for hosts files which have undergone the extremely thorough filtering and formatting process which Steven Black maintains with his repo. It is beyond the capability of this repo, maintained solely by myself, to guarantee any given third-party hosts file will not break your system or otherwise have adverse outcomes.
