### ISSUE TITLE
[question] need little help with small script

### ISSUE THREAD

**Issue by dnmTX** [ScriptTiger/Unified-Hosts-AutoUpdate#9]
@ScriptTiger  very sorry to bother you man but i know you are good with scripts so i decided to seek your wisdom on that matter.So long story short.Per your advice to switch to dnsmasq etc. i loaded custom firmware to my router which has dnsmsq installed in it.So far so good but due to small cache(only 8mb) and using ready script(found it in one forum) that is using sim link to load the host file,which loaded once and didn't want to reload it anymore i decided to keep the hosts file in usb connected to the router.This way is working  fine and i pointed dnsmasq to use that hosts file instead of the originial. Now i'm working on creating small script just to update the file whenever update is available.I'm using plink.exe which is part of PuTTY to SSH to the router.This is the content of the script so far,any advise on how to make it better will be greatly appreciated:
" @echo off

"D:\Program Files\PuTTY\plink.exe" -ssh admin@192.168.1.1 -pw ****** -m D:\test.sh

pause

start C:\Windows\System32\ipconfig.exe
ipconfig /flushdns

pause"

The content in TEST.SH is:
#!/bin/sh
wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts -O /media/AiDisk_a1/Hosts/add.hosts
killall dnsmasq
/usr/sbin/dnsmasq

What i need is after finish updating the file with plink.exe to flush the dns cache without the additional cmd window to flash for a second and overall whatever else you could advise.Thank you.

**Comment by ScriptTiger** [comment]
No worries, @dnmTX. The extra window that is popping up is from the "start" command issued. When you issue "start C:\Windows\System32\ipconfig.exe", it's opening a new command process in a new window solely to show you the network settings of your machine, and then closes. When you issue "C:\Windows\System32\ipconfig.exe" by itself without any switches or other parameters, it's solely a diagnostic tool and nothing else, it doesn't perform any action beyond showing you the network settings. So if you just remove that line entirely and just keep it "ipconfig /flushdns", you'll be good to go.

P.S.: I actually have an offline repo I haven't made public yet for a network device updater that can update multiple network devices simultaneously using HTTP(S), telnet, and/or ssh, I started it after someone on Steven's repo mentioned it to me before. I haven't published it yet because I have had a lot going on recently and haven't been able to finish it off. The main goal is to make it workable with the widest range of network devices, so the script itself must be modified to accommodate the different commands from device to device, but also make it as easy as possible to do so and allow for the blacklist data to be injected at any given point in the process as dictated by the user. So far my script is actually a bit like my own version of Expect and I ended up forking it to another repo for general network device automation. But other than being sidetracked with another scripting project, I have also had a lot going on personally the last month. So my offline repos are mounting a bit at the moment, but the next time I get some alone time with my computer I definitely want to release some more stuff, to also include that general purpose hosts manager i still have in the works.

**Comment by dnmTX** [comment]
@ScriptTiger  removing the "start...." line fixed it,now it's much much better.Thank you very much for the help,and sorry again that i had to bother you with such a small thing.Looking forward to check out that new script of yours whenever you finish it.
Closing........

**Comment by ScriptTiger** [comment]
Any time, @dnmTX. I hope dnsmasq works out for you. And since it was my suggestion in the first place, it's the least I can do to follow through and make sure it's working out for you. After you have it running for a while, maybe you can also leave a comment over on the other issue (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/5) about what you think about it and how it relates to your issue and how it helps you, etc., just to keep all the information together. Maybe your thoughts could help others in the same situation and give them more insight as to the option you chose to deal with it.

**Comment by ScriptTiger** [comment]
@dnmTX, are you still using dnsmasq? I'd like to optimize my current dnsmasq format if possible and dramatically reduce the list size.

Right now my dnsmasq format uses the following format:

`address=/zarget.com/0.0.0.0`

Does this block the domain and all subdomains? I have also seen the following:

`address=/.zarget.com/0.0.0.0`

Do I need both of these to block a domain and all subdomains? If you can let me know how this works, I can get rid of all redundant subdomains and possibly reduce the list size as well as prevent possible conflicts. If you're not sure yourself, maybe you could just test it real quick? I'd really appreciate it and in the end it would massively help out everyone using the list.

**Comment by dnmTX** [comment]
@ScriptTiger  dnsmasq can not read wildcards,of any kind,period.It's just how it is coded by the developer. There is one exception only and it's called PI-HOLE.There,the developers are using their own modified version of dnsmasq and were able to achieve that.Which,in fact led to another...obstacle,every lists had to be modified for their own version of dnsmasq.
So... `address=/zarget.com/0.0.0.0` will block `zarget.com` ONLY
if you want to block some subdomain,it has to be `address=/cdn.zarget.com/0.0.0.0`
`address=/.zarget.com/0.0.0.0` most likely will give some error that cannot be read.Bottom line,will not block anything.
I don't use that format `address=/domain.com/0.0.0.0` on my dnsmasq as this only can be placed in it's `config file`.And on routers(btw if you remember all my lists are placed in my router and managed by dnsmasq there) there is a hard limit on how many lines you can place in the `config file`.So,put it simply,it's not possible even to place a small lists(3000 lines for example)there.
Dnsmasq is perfectly capable of reading regular hosts files( in `0.0.0.0 domain.com` format) with the command:
`addn-hosts=/path/to/your/hosts.file` and you can add as many as you want(no limits there).
Of course,it's always good idea to have some little script to clean the comments and what not before you give it to dnsmasq.
So this is what i do and it works like charm. Here is a screenshot from my router's log:

![Syslogd](https://user-images.githubusercontent.com/34774426/63805470-1fe6ea80-c8df-11e9-85bb-13bb1d27792a.png)

Hope this will help you on how to proceed further. Cheers 👍 

P.S. My opinion on the subject is:
Creating such a lists in `address=/domain.com/0.0.0.0` for dnsmasq is useless.
Anyone who knows how to operate with dnsmasq will not go through all that hassle adding hunfreds of lines to their `config files`,using more complex scripts and do that every week or so(to update their lists) if they can simply download regular lists and point dnsmasq to it.
Maybe a clean lists(no comments and whatever else,just the domains only) and a note that says:
"DNSMASQ ready clean lists.Download it to your system and point dnsmasq to it with the command:
`addn-hosts=/path/to/your/clean.list`" will work better.

**Comment by ScriptTiger** [comment]
@dnmTX, yes, that helps a lot, thank you! I didn't know dnsmasq could read hosts files like that, so I'll definitely remember that when others bring up issues about it. Since it only takes me a couple seconds to generate the current dnsmasq files along with all the other formats, I'll just keep it as is for anyone that wants it.
